Repository graceuche/northeastern-final-project, pull requests merged in 2022-05, with the labels that each got.

#13 resolves #6
  .deepnote/id-resolver.json
  visual_analysis.ipynb
Labels: Tidying up issue

#17 Update README.md
  README.md
Labels: documentation

#20 Add a board image file via upload
  Grace-board.png
Labels: documentation

#22 Update README.md
  README.md
Labels: documentation

#23 Update README.md
  README.md
Labels: documentation

#24 Update README.md
  README.md
Labels: documentation

#26 Update README.md
  README.md
Labels: documentation

#18 Add more complex data exploration charts, e.g., regression
  init.ipynb
  visual_analysis.ipynb
Labels: Data Visualization

#29 Personal Rationale
  README.md
Labels: documentation

#31 Markdown comments
  init.ipynb
  visual_analysis.ipynb
Labels: Data Visualization

#30 Adds regression plots
  init.ipynb
  visual_analysis.ipynb
Labels: Data Visualization

#32 Update README.md
  README.md
Labels: documentation
